- hosts: "web"
  become: true
  vars_files:
    - vars/default.yaml
  tasks:
  
  # Install apache2 webserver
  - name: "install apache version {{ _version }}"
    apt: name="apache2={{ _version }}-*" state=present update_cache=yes
    when: _version is defined
   

  # Configure Apache2
  - name: Copy over the conf to apache
    copy:
      src: files/apache2.conf-{{ _version }}
      dest: "/etc/apache2/apache2.conf"
      owner: root
      group: root
      mode: 060
    when: _version is defined
    notify: restart-apache


  # Check Apache2 PID status
  - name: Check PID of existing apache process
    shell: "ps -ef | grep apache2"
    register: apache2_status

  - debug: "msg={{ apache2_status.stdout }}"


  # Import external handler file or define new handlers
  handlers:

  - import_tasks: handlers/main.yml

  - name: restart-apache
    service:
      name: apache2
      state: restarted

