- hosts: "database"
  become: true

  # Encrypted data from anisible-vault
  vars_files:
    - vars/cred.yaml

  tasks:

  - name: Install python packages
    apt: name={{ item }} update_cache=yes state=latest
    loop: [ 'python3-apt', 'pip', 'python3-dev', 'python3-pymysql', 'default-libmysqlclient-dev', 'build-essential' ]

  - name: Install mysql server and client
    apt: name={{ item }} update_cache=yes state=latest
    loop: [ 'mysql-server', 'mysql-client' ]

  - name: Start mysql service 
    service:
      name: mysql
      state: started 
      enabled: true

  - name: Update mysql root password for all root accounts
    mysql_user:
      name: root
      password: "{{ mysql_root_password }}"
      state: present
      login_host: "localhost"
      login_user: "root"
      login_password: "mypassword"
      login_unix_socket: /var/run/mysqld/mysqld.sock

  handlers:
  - name: resart-mysql
    service:
      name: mysql
      state: restarted
